alias y="env PATH=/usr/bin yaourt"
alias yup="y -Syu --aur"
alias yr="y -Rscd"
alias yi="y -S"
alias ys="y -Ss"

alias am="runuser -u aur -g aur -- env -i PATH=/usr/bin aurman"
alias amup="am -Syu"
alias amr="am -Rscd"
alias ami="am -S"
alias ams="am -Ss"
