size = "2650x1440"
vsync = true
fork = true
multigrid = true

[font]
normal = [
	"CaskaydiaCove Nerd Font Mono",
	"Lilex Nerd Font Mono",
	"ComicShannsMono Nerd Font",
	"MonoLisa Nerd Font Mono",
]
size = 11
hinting = "full"
edging = "antialias"
