[*]
np = 1
fa = on
fit = on
fit-ctx = 131072
ctx-size = 131072
fit-target = 256
n-gpu-layers = 999
no-host = true
batch-size = 2048
ubatch-size = 512
cache-ram = 16384
temp = 0.7
top-p = 0.95
top-k = 25
min-p = 0.05
presence-penalty = 0.2
repeat-penalty = 1.05
no-mmap = true
direct-io = true
prio = 3
prio-batch = 3
spec-draft-prio = 3
threads = 16
threads-batch = 16
cache-type-k = q8_0
cache-type-v = q8_0
kv-unified = true
cache-type-k-draft = q8_0
cache-type-v-draft = q8_0
reasoning-budget = 512
reasoning-budget-message = Okay, I have enough information to answer.
reasoning-preserve = true
no-warmup = true
no-mmproj = true
ctx-checkpoints = 64
spec-type = draft-mtp
spec-draft-n-max = 1
spec-draft-n-min = 0.0

[mudler/Ornith-1.0-35B-APEX-GGUF:COMPACT]
hf = mudler/Ornith-1.0-35B-APEX-GGUF:Ornith-1.0-35B-APEX-I-Compact
hfd = a4lg/Qwen3.5-35B-A3B-MTP-ONLY-GGUF:Q8_0

; spec-type = ngram-mod
spec-ngram-mod-n-match = 24
spec-ngram-mod-n-min = 8
spec-ngram-mod-n-max = 16
cache-type-k = q8_0
cache-type-v = q8_0
cache-type-k-draft = f16
cache-type-v-draft = f16

[mradermacher/Reasoning-Medical-27B-i1-GGUF:Q4_K_M]
spec-type = ngram-mod
spec-ngram-mod-n-match = 24
spec-ngram-mod-n-min = 8
spec-ngram-mod-n-max = 16

